// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  CreateExpenseData,
  CreateExpenseResponses,
  CreateSettlementData,
  CreateSettlementResponses,
  CreateWorkspaceData,
  CreateWorkspaceResponses,
  DeleteExpenseData,
  DeleteExpenseResponses,
  GetActivityData,
  GetActivityResponses,
  GetAnalyticsData,
  GetAnalyticsResponses,
  GetBalancesData,
  GetBalancesResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetDebtsData,
  GetDebtsResponses,
  GetExpenseData,
  GetExpenseResponses,
  GetFriendsBalancesData,
  GetFriendsBalancesResponses,
  GetGlobalAnalyticsData,
  GetGlobalAnalyticsResponses,
  GetGlobalBalancesData,
  GetGlobalBalancesResponses,
  GetUserByIdData,
  GetUserByIdResponses,
  GetWorkspaceData,
  GetWorkspaceMembersData,
  GetWorkspaceMembersResponses,
  GetWorkspaceResponses,
  GetWorkspacesData,
  GetWorkspacesResponses,
  InviteMemberData,
  InviteMemberResponses,
  ListSettlementsData,
  ListSettlementsResponses,
  ListWorkspaceExpensesData,
  ListWorkspaceExpensesResponses,
  UpdateExpenseData,
  UpdateExpenseResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get current authenticated user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/users/me',
    ...options,
  });

/**
 * Get a user by ID
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
): RequestResult<GetUserByIdResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetUserByIdResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/users/{userId}',
    ...options,
  });

/**
 * List workspaces for current user
 */
export const getWorkspaces = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkspacesData, ThrowOnError>,
): RequestResult<GetWorkspacesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetWorkspacesResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces',
    ...options,
  });

/**
 * Create a new workspace
 */
export const createWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkspaceData, ThrowOnError>,
): RequestResult<CreateWorkspaceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CreateWorkspaceResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get workspace by ID
 */
export const getWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkspaceData, ThrowOnError>,
): RequestResult<GetWorkspaceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetWorkspaceResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}',
    ...options,
  });

/**
 * List members of a workspace
 */
export const getWorkspaceMembers = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkspaceMembersData, ThrowOnError>,
): RequestResult<GetWorkspaceMembersResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetWorkspaceMembersResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/members',
    ...options,
  });

/**
 * Invite a user to a workspace by email
 */
export const inviteMember = <ThrowOnError extends boolean = false>(
  options: Options<InviteMemberData, ThrowOnError>,
): RequestResult<InviteMemberResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<InviteMemberResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/members',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List expenses in a workspace
 */
export const listWorkspaceExpenses = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkspaceExpensesData, ThrowOnError>,
): RequestResult<ListWorkspaceExpensesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ListWorkspaceExpensesResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/expenses',
    ...options,
  });

/**
 * Add a new expense to a workspace
 */
export const createExpense = <ThrowOnError extends boolean = false>(
  options: Options<CreateExpenseData, ThrowOnError>,
): RequestResult<CreateExpenseResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CreateExpenseResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/expenses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an expense
 */
export const deleteExpense = <ThrowOnError extends boolean = false>(
  options: Options<DeleteExpenseData, ThrowOnError>,
): RequestResult<DeleteExpenseResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<DeleteExpenseResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/expenses/{expenseId}',
    ...options,
  });

/**
 * Get expense by ID
 */
export const getExpense = <ThrowOnError extends boolean = false>(
  options: Options<GetExpenseData, ThrowOnError>,
): RequestResult<GetExpenseResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetExpenseResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/expenses/{expenseId}',
    ...options,
  });

/**
 * Update an expense
 */
export const updateExpense = <ThrowOnError extends boolean = false>(
  options: Options<UpdateExpenseData, ThrowOnError>,
): RequestResult<UpdateExpenseResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<UpdateExpenseResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/expenses/{expenseId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get net balances for a workspace
 */
export const getBalances = <ThrowOnError extends boolean = false>(
  options: Options<GetBalancesData, ThrowOnError>,
): RequestResult<GetBalancesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetBalancesResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/balances',
    ...options,
  });

/**
 * Get debts for a workspace, optionally simplified
 */
export const getDebts = <ThrowOnError extends boolean = false>(
  options: Options<GetDebtsData, ThrowOnError>,
): RequestResult<GetDebtsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetDebtsResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/balances/debts',
    ...options,
  });

/**
 * List settlements in a workspace
 */
export const listSettlements = <ThrowOnError extends boolean = false>(
  options: Options<ListSettlementsData, ThrowOnError>,
): RequestResult<ListSettlementsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ListSettlementsResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/settlements',
    ...options,
  });

/**
 * Record a settlement
 */
export const createSettlement = <ThrowOnError extends boolean = false>(
  options: Options<CreateSettlementData, ThrowOnError>,
): RequestResult<CreateSettlementResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CreateSettlementResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/settlements',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get spending analytics for a workspace
 */
export const getAnalytics = <ThrowOnError extends boolean = false>(
  options: Options<GetAnalyticsData, ThrowOnError>,
): RequestResult<GetAnalyticsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetAnalyticsResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/analytics',
    ...options,
  });

/**
 * Get global analytics across all workspaces
 */
export const getGlobalAnalytics = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalAnalyticsData, ThrowOnError>,
): RequestResult<GetGlobalAnalyticsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetGlobalAnalyticsResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/analytics',
    ...options,
  });

/**
 * Get global balances across all workspaces
 */
export const getGlobalBalances = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalBalancesData, ThrowOnError>,
): RequestResult<GetGlobalBalancesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetGlobalBalancesResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/balances',
    ...options,
  });

/**
 * Get recent activity
 */
export const getActivity = <ThrowOnError extends boolean = false>(
  options: Options<GetActivityData, ThrowOnError>,
): RequestResult<GetActivityResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetActivityResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/workspaces/{workspaceId}/activity',
    ...options,
  });

/**
 * Get global balances with friends
 */
export const getFriendsBalances = <ThrowOnError extends boolean = false>(
  options?: Options<GetFriendsBalancesData, ThrowOnError>,
): RequestResult<GetFriendsBalancesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetFriendsBalancesResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'session',
        type: 'apiKey',
      },
    ],
    url: '/balances/friends',
    ...options,
  });
