// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type ProblemDetail = {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  requestId?: string;
  traceId?: string;
};

export type User = {
  id: string;
  email: string;
  name: string;
  avatarUrl?: string | null;
};

export type Workspace = {
  id: string;
  name: string;
  defaultCurrency: string;
  createdAt: string;
};

export type Expense = {
  id: string;
  workspaceId: string;
  description: string;
  amount: number;
  date: string;
  splitType: 'EQUAL' | 'EXACT' | 'PERCENTAGE';
  paidBy: string;
  createdAt: string;
  splits?: Array<ExpenseSplit>;
  category: string;
  currency: string;
  type?: 'EXPENSE' | 'TRANSFER';
  tags?: Array<string>;
  recurringInterval?: 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
};

export type ExpenseSplit = {
  id: string;
  userId: string;
  amountOwed: number;
  amountPaid: number;
};

export type Settlement = {
  id: string;
  workspaceId: string;
  payerId: string;
  payeeId: string;
  amount: number;
  date: string;
  createdAt: string;
};

export type Balance = {
  byCurrency: Array<{
    currency: string;
    total: number;
    owedToYou: number;
    youOwe: number;
    perMember: Array<{
      userId: string;
      net: number;
    }>;
  }>;
};

export type SimplifiedDebt = {
  debtor: string;
  creditor: string;
  amount: number;
  currency: string;
};

export type Analytics = {
  byCurrency: Array<{
    currency: string;
    totalSpend: number;
    expenseCount: number;
    spendByMember: Array<{
      userId: string;
      name: string;
      amount: number;
    }>;
    spendOverTime: Array<{
      date: string;
      amount: number;
    }>;
    topCategories: Array<{
      description: string;
      count: number;
      total: number;
    }>;
    trueSpending: number;
    cashOut: number;
    received: number;
    paid: number;
    todaySpend: number;
    thisMonthSpend: number;
    tagsAnalysis?: Array<{
      tag?: string;
      total?: number;
    }>;
  }>;
};

export type PayerInfo = {
  userId: string;
  amount: number;
};

export type CreateExpenseDto = {
  description: string;
  amount: number;
  date: string;
  splitType: 'EQUAL' | 'EXACT' | 'PERCENTAGE';
  groupId: string;
  category?: string;
  currency?: string;
  type?: 'EXPENSE' | 'TRANSFER';
  tags?: Array<string>;
  recurringInterval?: 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  payers: Array<PayerInfo>;
  exactAmounts?: Array<{
    userId?: string;
    amount?: number;
  }>;
  percentages?: Array<{
    userId?: string;
    percentage?: number;
  }>;
};

export type CreateSettlementDto = {
  payeeId: string;
  /**
   * Optional custom amount. If omitted, settles the entire debt.
   */
  amount?: number;
  date?: string;
};

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type GetCurrentUserResponses = {
  /**
   * Current user
   */
  200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: '/users/{userId}';
};

export type GetUserByIdResponses = {
  /**
   * User object
   */
  200: User;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetWorkspacesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/workspaces';
};

export type GetWorkspacesResponses = {
  /**
   * A list of workspaces
   */
  200: Array<Workspace>;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type CreateWorkspaceData = {
  body: {
    name: string;
    defaultCurrency?: string;
  };
  path?: never;
  query?: never;
  url: '/workspaces';
};

export type CreateWorkspaceResponses = {
  /**
   * Workspace created
   */
  201: Workspace;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type GetWorkspaceData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}';
};

export type GetWorkspaceResponses = {
  /**
   * Workspace object
   */
  200: Workspace;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type GetWorkspaceMembersData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/members';
};

export type GetWorkspaceMembersResponses = {
  /**
   * A list of members
   */
  200: Array<User>;
};

export type GetWorkspaceMembersResponse =
  GetWorkspaceMembersResponses[keyof GetWorkspaceMembersResponses];

export type InviteMemberData = {
  body: {
    email: string;
  };
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/members';
};

export type InviteMemberResponses = {
  /**
   * User invited
   */
  201: {
    success?: boolean;
  };
};

export type InviteMemberResponse = InviteMemberResponses[keyof InviteMemberResponses];

export type ListWorkspaceExpensesData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: {
    search?: string;
    q?: string;
    currency?: string;
    category?: string;
    sortBy?: string;
    tags?: string;
  };
  url: '/workspaces/{workspaceId}/expenses';
};

export type ListWorkspaceExpensesResponses = {
  /**
   * List of expenses
   */
  200: Array<Expense>;
};

export type ListWorkspaceExpensesResponse =
  ListWorkspaceExpensesResponses[keyof ListWorkspaceExpensesResponses];

export type CreateExpenseData = {
  body: {
    description: string;
    amount: number;
    date: string;
    splitType: 'EQUAL' | 'EXACT' | 'PERCENTAGE';
    paidBy: string;
    participants: Array<string>;
    exactAmounts?: Array<{
      userId: string;
      amount: number;
    }>;
    category: string;
    percentages?: Array<{
      userId: string;
      percentage: number;
    }>;
    currency: string;
  };
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/expenses';
};

export type CreateExpenseResponses = {
  /**
   * Expense created
   */
  201: Expense;
};

export type CreateExpenseResponse = CreateExpenseResponses[keyof CreateExpenseResponses];

export type DeleteExpenseData = {
  body?: never;
  path: {
    expenseId: string;
  };
  query?: never;
  url: '/expenses/{expenseId}';
};

export type DeleteExpenseResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteExpenseResponse = DeleteExpenseResponses[keyof DeleteExpenseResponses];

export type GetExpenseData = {
  body?: never;
  path: {
    expenseId: string;
  };
  query?: never;
  url: '/expenses/{expenseId}';
};

export type GetExpenseResponses = {
  /**
   * Expense object
   */
  200: Expense;
};

export type GetExpenseResponse = GetExpenseResponses[keyof GetExpenseResponses];

export type UpdateExpenseData = {
  body: {
    description?: string;
    amount?: number;
    date?: string;
    splitType?: 'EQUAL' | 'EXACT' | 'PERCENTAGE';
    paidBy?: string;
    participants?: Array<string>;
    exactAmounts?: Array<{
      userId?: string;
      amount?: number;
    }>;
    category?: string;
    percentages?: Array<{
      userId?: string;
      percentage?: number;
    }>;
    currency?: string;
  };
  path: {
    expenseId: string;
  };
  query?: never;
  url: '/expenses/{expenseId}';
};

export type UpdateExpenseResponses = {
  /**
   * Updated expense
   */
  200: Expense;
};

export type UpdateExpenseResponse = UpdateExpenseResponses[keyof UpdateExpenseResponses];

export type GetBalancesData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/balances';
};

export type GetBalancesResponses = {
  /**
   * Balance summary
   */
  200: Balance;
};

export type GetBalancesResponse = GetBalancesResponses[keyof GetBalancesResponses];

export type GetDebtsData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: {
    simplified?: boolean;
  };
  url: '/workspaces/{workspaceId}/balances/debts';
};

export type GetDebtsResponses = {
  /**
   * Debt list
   */
  200: Array<SimplifiedDebt>;
};

export type GetDebtsResponse = GetDebtsResponses[keyof GetDebtsResponses];

export type ListSettlementsData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/settlements';
};

export type ListSettlementsResponses = {
  /**
   * List of settlements
   */
  200: Array<Settlement>;
};

export type ListSettlementsResponse = ListSettlementsResponses[keyof ListSettlementsResponses];

export type CreateSettlementData = {
  body: {
    payerId: string;
    payeeId: string;
    amount: number;
    date: string;
  };
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/settlements';
};

export type CreateSettlementResponses = {
  /**
   * Settlement recorded
   */
  201: Settlement;
};

export type CreateSettlementResponse = CreateSettlementResponses[keyof CreateSettlementResponses];

export type GetAnalyticsData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/analytics';
};

export type GetAnalyticsResponses = {
  /**
   * Analytics data
   */
  200: Analytics;
};

export type GetAnalyticsResponse = GetAnalyticsResponses[keyof GetAnalyticsResponses];

export type GetGlobalAnalyticsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/analytics';
};

export type GetGlobalAnalyticsResponses = {
  /**
   * Global Analytics data
   */
  200: Analytics;
};

export type GetGlobalAnalyticsResponse =
  GetGlobalAnalyticsResponses[keyof GetGlobalAnalyticsResponses];

export type GetGlobalBalancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/balances';
};

export type GetGlobalBalancesResponses = {
  /**
   * Global Balance data
   */
  200: Balance;
};

export type GetGlobalBalancesResponse =
  GetGlobalBalancesResponses[keyof GetGlobalBalancesResponses];

export type GetActivityData = {
  body?: never;
  path: {
    workspaceId: string;
  };
  query?: never;
  url: '/workspaces/{workspaceId}/activity';
};

export type GetActivityResponses = {
  /**
   * OK
   */
  200: Array<{
    id?: string;
    type?: 'EXPENSE' | 'SETTLEMENT';
    description?: string;
    amount?: number;
    date?: string;
    actionBy?: string;
  }>;
};

export type GetActivityResponse = GetActivityResponses[keyof GetActivityResponses];

export type GetFriendsBalancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/balances/friends';
};

export type GetFriendsBalancesResponses = {
  /**
   * OK
   */
  200: Array<{
    userId?: string;
    name?: string;
    avatarUrl?: string;
    netBalance?: number;
    currency?: string;
  }>;
};

export type GetFriendsBalancesResponse =
  GetFriendsBalancesResponses[keyof GetFriendsBalancesResponses];
