// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  createExpense,
  createSettlement,
  createWorkspace,
  deleteExpense,
  getActivity,
  getAnalytics,
  getBalances,
  getCurrentUser,
  getDebts,
  getExpense,
  getFriendsBalances,
  getGlobalAnalytics,
  getGlobalBalances,
  getUserById,
  getWorkspace,
  getWorkspaceMembers,
  getWorkspaces,
  inviteMember,
  listSettlements,
  listWorkspaceExpenses,
  type Options,
  updateExpense,
} from '../sdk.gen';
import type {
  CreateExpenseData,
  CreateExpenseResponse,
  CreateSettlementData,
  CreateSettlementResponse,
  CreateWorkspaceData,
  CreateWorkspaceResponse,
  DeleteExpenseData,
  DeleteExpenseResponse,
  GetActivityData,
  GetActivityResponse,
  GetAnalyticsData,
  GetAnalyticsResponse,
  GetBalancesData,
  GetBalancesResponse,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetDebtsData,
  GetDebtsResponse,
  GetExpenseData,
  GetExpenseResponse,
  GetFriendsBalancesData,
  GetFriendsBalancesResponse,
  GetGlobalAnalyticsData,
  GetGlobalAnalyticsResponse,
  GetGlobalBalancesData,
  GetGlobalBalancesResponse,
  GetUserByIdData,
  GetUserByIdResponse,
  GetWorkspaceData,
  GetWorkspaceMembersData,
  GetWorkspaceMembersResponse,
  GetWorkspaceResponse,
  GetWorkspacesData,
  GetWorkspacesResponse,
  InviteMemberData,
  InviteMemberResponse,
  ListSettlementsData,
  ListSettlementsResponse,
  ListWorkspaceExpensesData,
  ListWorkspaceExpensesResponse,
  UpdateExpenseData,
  UpdateExpenseResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
  createQueryKey('getCurrentUser', options);

/**
 * Get current authenticated user
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) =>
  queryOptions<
    GetCurrentUserResponse,
    DefaultError,
    GetCurrentUserResponse,
    ReturnType<typeof getCurrentUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentUserQueryKey(options),
  });

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) =>
  createQueryKey('getUserById', options);

/**
 * Get a user by ID
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) =>
  queryOptions<
    GetUserByIdResponse,
    DefaultError,
    GetUserByIdResponse,
    ReturnType<typeof getUserByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserByIdQueryKey(options),
  });

export const getWorkspacesQueryKey = (options?: Options<GetWorkspacesData>) =>
  createQueryKey('getWorkspaces', options);

/**
 * List workspaces for current user
 */
export const getWorkspacesOptions = (options?: Options<GetWorkspacesData>) =>
  queryOptions<
    GetWorkspacesResponse,
    DefaultError,
    GetWorkspacesResponse,
    ReturnType<typeof getWorkspacesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaces({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspacesQueryKey(options),
  });

/**
 * Create a new workspace
 */
export const createWorkspaceMutation = (
  options?: Partial<Options<CreateWorkspaceData>>,
): UseMutationOptions<CreateWorkspaceResponse, DefaultError, Options<CreateWorkspaceData>> => {
  const mutationOptions: UseMutationOptions<
    CreateWorkspaceResponse,
    DefaultError,
    Options<CreateWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkspaceQueryKey = (options: Options<GetWorkspaceData>) =>
  createQueryKey('getWorkspace', options);

/**
 * Get workspace by ID
 */
export const getWorkspaceOptions = (options: Options<GetWorkspaceData>) =>
  queryOptions<
    GetWorkspaceResponse,
    DefaultError,
    GetWorkspaceResponse,
    ReturnType<typeof getWorkspaceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspace({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspaceQueryKey(options),
  });

export const getWorkspaceMembersQueryKey = (options: Options<GetWorkspaceMembersData>) =>
  createQueryKey('getWorkspaceMembers', options);

/**
 * List members of a workspace
 */
export const getWorkspaceMembersOptions = (options: Options<GetWorkspaceMembersData>) =>
  queryOptions<
    GetWorkspaceMembersResponse,
    DefaultError,
    GetWorkspaceMembersResponse,
    ReturnType<typeof getWorkspaceMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaceMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspaceMembersQueryKey(options),
  });

/**
 * Invite a user to a workspace by email
 */
export const inviteMemberMutation = (
  options?: Partial<Options<InviteMemberData>>,
): UseMutationOptions<InviteMemberResponse, DefaultError, Options<InviteMemberData>> => {
  const mutationOptions: UseMutationOptions<
    InviteMemberResponse,
    DefaultError,
    Options<InviteMemberData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await inviteMember({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listWorkspaceExpensesQueryKey = (options: Options<ListWorkspaceExpensesData>) =>
  createQueryKey('listWorkspaceExpenses', options);

/**
 * List expenses in a workspace
 */
export const listWorkspaceExpensesOptions = (options: Options<ListWorkspaceExpensesData>) =>
  queryOptions<
    ListWorkspaceExpensesResponse,
    DefaultError,
    ListWorkspaceExpensesResponse,
    ReturnType<typeof listWorkspaceExpensesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWorkspaceExpenses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listWorkspaceExpensesQueryKey(options),
  });

/**
 * Add a new expense to a workspace
 */
export const createExpenseMutation = (
  options?: Partial<Options<CreateExpenseData>>,
): UseMutationOptions<CreateExpenseResponse, DefaultError, Options<CreateExpenseData>> => {
  const mutationOptions: UseMutationOptions<
    CreateExpenseResponse,
    DefaultError,
    Options<CreateExpenseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createExpense({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an expense
 */
export const deleteExpenseMutation = (
  options?: Partial<Options<DeleteExpenseData>>,
): UseMutationOptions<DeleteExpenseResponse, DefaultError, Options<DeleteExpenseData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteExpenseResponse,
    DefaultError,
    Options<DeleteExpenseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteExpense({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExpenseQueryKey = (options: Options<GetExpenseData>) =>
  createQueryKey('getExpense', options);

/**
 * Get expense by ID
 */
export const getExpenseOptions = (options: Options<GetExpenseData>) =>
  queryOptions<
    GetExpenseResponse,
    DefaultError,
    GetExpenseResponse,
    ReturnType<typeof getExpenseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExpense({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExpenseQueryKey(options),
  });

/**
 * Update an expense
 */
export const updateExpenseMutation = (
  options?: Partial<Options<UpdateExpenseData>>,
): UseMutationOptions<UpdateExpenseResponse, DefaultError, Options<UpdateExpenseData>> => {
  const mutationOptions: UseMutationOptions<
    UpdateExpenseResponse,
    DefaultError,
    Options<UpdateExpenseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateExpense({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBalancesQueryKey = (options: Options<GetBalancesData>) =>
  createQueryKey('getBalances', options);

/**
 * Get net balances for a workspace
 */
export const getBalancesOptions = (options: Options<GetBalancesData>) =>
  queryOptions<
    GetBalancesResponse,
    DefaultError,
    GetBalancesResponse,
    ReturnType<typeof getBalancesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBalances({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBalancesQueryKey(options),
  });

export const getDebtsQueryKey = (options: Options<GetDebtsData>) =>
  createQueryKey('getDebts', options);

/**
 * Get debts for a workspace, optionally simplified
 */
export const getDebtsOptions = (options: Options<GetDebtsData>) =>
  queryOptions<
    GetDebtsResponse,
    DefaultError,
    GetDebtsResponse,
    ReturnType<typeof getDebtsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDebts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDebtsQueryKey(options),
  });

export const listSettlementsQueryKey = (options: Options<ListSettlementsData>) =>
  createQueryKey('listSettlements', options);

/**
 * List settlements in a workspace
 */
export const listSettlementsOptions = (options: Options<ListSettlementsData>) =>
  queryOptions<
    ListSettlementsResponse,
    DefaultError,
    ListSettlementsResponse,
    ReturnType<typeof listSettlementsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSettlements({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSettlementsQueryKey(options),
  });

/**
 * Record a settlement
 */
export const createSettlementMutation = (
  options?: Partial<Options<CreateSettlementData>>,
): UseMutationOptions<CreateSettlementResponse, DefaultError, Options<CreateSettlementData>> => {
  const mutationOptions: UseMutationOptions<
    CreateSettlementResponse,
    DefaultError,
    Options<CreateSettlementData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSettlement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAnalyticsQueryKey = (options: Options<GetAnalyticsData>) =>
  createQueryKey('getAnalytics', options);

/**
 * Get spending analytics for a workspace
 */
export const getAnalyticsOptions = (options: Options<GetAnalyticsData>) =>
  queryOptions<
    GetAnalyticsResponse,
    DefaultError,
    GetAnalyticsResponse,
    ReturnType<typeof getAnalyticsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAnalytics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAnalyticsQueryKey(options),
  });

export const getGlobalAnalyticsQueryKey = (options?: Options<GetGlobalAnalyticsData>) =>
  createQueryKey('getGlobalAnalytics', options);

/**
 * Get global analytics across all workspaces
 */
export const getGlobalAnalyticsOptions = (options?: Options<GetGlobalAnalyticsData>) =>
  queryOptions<
    GetGlobalAnalyticsResponse,
    DefaultError,
    GetGlobalAnalyticsResponse,
    ReturnType<typeof getGlobalAnalyticsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGlobalAnalytics({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGlobalAnalyticsQueryKey(options),
  });

export const getGlobalBalancesQueryKey = (options?: Options<GetGlobalBalancesData>) =>
  createQueryKey('getGlobalBalances', options);

/**
 * Get global balances across all workspaces
 */
export const getGlobalBalancesOptions = (options?: Options<GetGlobalBalancesData>) =>
  queryOptions<
    GetGlobalBalancesResponse,
    DefaultError,
    GetGlobalBalancesResponse,
    ReturnType<typeof getGlobalBalancesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGlobalBalances({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGlobalBalancesQueryKey(options),
  });

export const getActivityQueryKey = (options: Options<GetActivityData>) =>
  createQueryKey('getActivity', options);

/**
 * Get recent activity
 */
export const getActivityOptions = (options: Options<GetActivityData>) =>
  queryOptions<
    GetActivityResponse,
    DefaultError,
    GetActivityResponse,
    ReturnType<typeof getActivityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActivity({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActivityQueryKey(options),
  });

export const getFriendsBalancesQueryKey = (options?: Options<GetFriendsBalancesData>) =>
  createQueryKey('getFriendsBalances', options);

/**
 * Get global balances with friends
 */
export const getFriendsBalancesOptions = (options?: Options<GetFriendsBalancesData>) =>
  queryOptions<
    GetFriendsBalancesResponse,
    DefaultError,
    GetFriendsBalancesResponse,
    ReturnType<typeof getFriendsBalancesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFriendsBalances({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFriendsBalancesQueryKey(options),
  });
